#!/usr/bin/env bash

ARCHIVES_DIR='docs/archives'

usage() {
    echo "Usage: ${0##*/} <command>" >&2
}

msg-info() {
    echo "[*] $(cat)"
}

msg-error() {
    echo "[Error] $(cat)" >&2
}

cmd-create() {
    local status

    local appname="${0##*/}"
    local dir="$(basename $(pwd))"
    if [[ "$appname" != "$dir" ]]; then
        msg-error <<< "$appname ディレクトリの直下で実行してください"
        exit 1
    fi

    local today="$(date +"%Y/%m/%d")"
    local article_dir="$ARCHIVES_DIR/$today"
    mkdir -p "$article_dir"
    status="$?"
    if [[ "$status" != 0 ]]; then
        msg-error <<< '記事ディレクトリの作成に失敗しました'
    fi

    local article="$article_dir/README.md"
    touch "$article"
    status="$?"
    if [[ "$status" != 0 ]]; then
        msg-error <<< '記事ファイルの作成に失敗しました'
    fi

    if [[ -s "$article" ]]; then
        read -p "ファイル($article)が既に存在するようです。上書きしますか?(y/N): " confirm
        case "$confirm" in
            [yY]*)
                ;;

            *)
                msg-error <<< '処理を中止します'
                exit 1
                ;;
        esac
    fi

    {
        echo "---"
        echo "title:"
        echo "description:"
        echo "---"
    } > "$article"

    echo >&2
    msg-info <<< "記事ファイルを作成しました: $article"
}

penguin-signpost() {
    local subcommand="$1"

    case "$subcommand" in

        'create')
            cmd-create
            ;;

        *)
            usage
            exit 1
            ;;

    esac
}

penguin-signpost "$@"
